### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by Adimaniac31** [solomonshalom/The-Abyss#36]
I was thinking of adding a light mode to the homepage atleast.Can you assign this issue to me?

**Comment by solomonshalom** [comment]
> I was thinking of adding a light mode to the homepage atleast.Can you assign this issue to me?

Shalom! @Adimaniac31,

We already do, it's just that it's completely based on the user's system preference but what did you have in mind?

**Comment by Adimaniac31** [comment]
I will add a toggle button between light or dark mode which will change background ground  a bit of text color and font style maybe

**Comment by solomonshalom** [comment]
> I will add a toggle button between light or dark mode which will change background ground a bit of text color and font style maybe

Shalom! @Adimaniac31,

Ah, well - go for it! I will assign you :D

P.S. There is no need to write additional logic for it, just use the one already implemented!

**Comment by solomonshalom** [comment]
> Yeah thanks it will be nice if you can add hacktoberfest label on it. Thanks

Sure!

**Comment by Adimaniac31** [comment]
Thanks

**Comment by Adimaniac31** [comment]
Hi, I am getting a issue i.e. " 'yarn' is not recognized as an internal or external command,
operable program or batch file." I tried installing yarn setting up ENV of npm changed execution-policies but I am still ending up with this issue, can you help me with it?

**Comment by solomonshalom** [comment]
> Hi, I am getting a issue i.e. " 'yarn' is not recognized as an internal or external command, operable program or batch file." I tried installing yarn setting up ENV of npm changed execution-policies but I am still ending up with this issue, can you help me with it? Also getting this issue
> 
> > Build error occurred
> > [Error: Your API key is invalid, please check you have copied it correctly.] {
> > type: 't',
> > code: 'auth/invalid-api-key',
> > a: null
> > }
> > error Command failed with exit code 1.
> > on yarn build

Shalom! @Adimaniac31,

OH, I don't think this is because of `Yarn` but because you didn't fill in the ENVs. Fill in the ENVs and let me know if that works :D

**Comment by Adimaniac31** [comment]
I added the ENVS so yarn build is working fine now but yarn start is still giving trouble.
![abyss](https://github.com/solomonshalom/The-Abyss/assets/130062050/c85911cc-8446-46aa-84c3-2bd135fba845)

**Comment by solomonshalom** [comment]
> I added the ENVS so yarn build is working fine now but yarn start is still giving trouble. ![abyss](https://user-images.githubusercontent.com/130062050/273383390-c85911cc-8446-46aa-84c3-2bd135fba845.png)

Shalom! @Adimaniac31,

AH! I apologize for the inconvenience, I was under the impression that it was patched but I just merged a security // bug-fix PR that will solve it! Sync your fork and it should be fixed, if not - let me know!

P.S. Don't have a good day, have a great day!

**Comment by Adimaniac31** [comment]
Hi, I fetched the upstream but the issue isn't solved yet. Can you guide me if there is something that I can do?

**Comment by solomonshalom** [comment]
> Hi, I fetched the upstream but the issue isn't solved yet. Can you guide me if there is something that I can do? PS: Have a great day.

Hmm, don't use Yarn but maybe either the `Next CLI` or `NPM`?

**Comment by Adimaniac31** [comment]
it is working with npx next start, but on clicking anonymous I can't go to next page but I will work on what I have now.Thanks.

**Comment by Adimaniac31** [comment]
Hii, its working now. There was a issue with package.json scripts, I changed yarn to next hope its okay. Also I have made the button and its working fine. Can you look into my PR?
Thanks, for overall help. Have a great day.

**Comment by solomonshalom** [comment]
> Hii, its working now. There was a issue with package.json scripts, I changed yarn to next hope its okay. Also I have made the button and its working fine. Can you look into my PR? Thanks, for overall help. Have a great day. PS:I got some issues with PR, can you help me with that? ![image](https://user-images.githubusercontent.com/130062050/273431095-bece89e9-68ce-4d23-bfe9-18e9030f37a2.png)

Shalom! @Adimaniac31,

It looks good! but is it possible for you could add it to the `Profile` section and also make sure to have a `toggle` as well but overall, it looks pretty cool!

P.S. Use the same style as the rest of the components, just so that it blends well! ALSO, I did push few changes to the `Main` branch so don't forget to sync your fork!

**Comment by Adimaniac31** [comment]
Sure, I will try making those changes in styling but I am not very sure about profile section since I cannot use the sign up and anonymous feature on localhost.Though, I will try it too and push the changes.And,yeah I will sync the fork.
Thanks.

**Comment by solomonshalom** [comment]
> Sure, I will try making those changes in styling but I am not very sure about profile section since I cannot use the sign up and anonymous feature on localhost.Though, I will try it too and push the changes.And,yeah I will sync the fork. Thanks.

OH, wait - you could just make a firebase account to do it or go to your fork's branch and press `.` on your keyboard to open up the IDE in the browser to do it :D

Always! Mate

**Comment by Adimaniac31** [comment]
Yeah, sure I will work on it then.

**Comment by solomonshalom** [comment]
> Yeah, sure I will work on it then.

Sure! Actually, to help you out w/ it - I made a PR on your fork, check it out and let me know!

**Comment by Adimaniac31** [comment]
Thanks for merging my PR. Also,if you need me for any other issue, I can work on it.

**Comment by solomonshalom** [comment]
> Thanks for merging my PR. Also,if you need me for any other issue, I can work on it.

OH, I actually didn't 😅 @Adimaniac31

**Comment by Adimaniac31** [comment]
Oh, sorry I actually received a mail from hacktoberfest and got excited 😅

**Comment by solomonshalom** [comment]
> Oh, sorry I actually received a mail from hacktoberfest and got excited 😅

OH, DWW - I was so confused too for a min 😅 but I am sure that few more commits and we will be good to go!

**Comment by Adimaniac31** [comment]
okk, do I have to add my name in Author.md and then send pr?

**Comment by solomonshalom** [comment]
> okk, do I have to add my name in Author.md and then send pr?

Shalom! @Adimaniac31,

There seem to be a few problems and I am not sure if I can merge your PR in the moment but I know that you worked really hard on it so, just to make your hacktoberfest participation count - could you make slight changes to the `README.md`?

I know that this is disappointing but I assure you that when we do implement it, I will tag you as the contributor! 

P.S. Yes! Go ahead and write your name & contributions in the `AUTHOR.md` (Make sure to add a small emoji too! 😁)

**Comment by Adimaniac31** [comment]
Yeah,sure just let me know when you merge it and can you tell what is the issue I may try to solve on my end.
Thanks.

**Comment by Adimaniac31** [comment]
Yeah, I made changes in Readme.md and AUTHORS.md. Can you look into it?
Also, I created a different branch for this but I already pushed changes to origin. Will it create any issue? If it does I will clone the project again.

**Comment by solomonshalom** [comment]
> Yeah, I made changes in Readme.md and AUTHORS.md. Can you look into it? Also, I created a different branch for this but I already pushed changes to origin. Will it create any issue? If it does I will clone the project again. PS: Yeah and it was nice working with you .🫵🗿 Can we connect on linkedin?

Shalom! @Adimaniac31,

Saw the PR, looks pretty good 😄 but could you make another branch w/ only the changes to the `AUTHOR.md` and `README.md`? If I were to merge the PR, it would also merge in the changes to the theme toggle which might cause a few disruptions 😬 

ALSO, Yep! here's my [Linkedin](https://www.linkedin.com/in/solomonlijo/) :D and it has been pretty cool working w/ you, Mate!

**Comment by Adimaniac31** [comment]
Sure, I made the changes also I have sent you connect request on Linkedin. My Linkedin id is Aditya Bhivgade.

**Comment by solomonshalom** [comment]
> Sure, I made the changes and sent a PR also I have sent you connect request on Linkedin. My Linkedin id is Aditya Bhivgade.

Ah! Merged the PR and will accept the request :D 

P.S. Thank you so much!! Happy hacktoberfest!

**Comment by Adimaniac31** [comment]
Yeah Thanks man.🫵🗿
